# --------------------------
# Stage 1: Build the backend
# --------------------------
FROM node:20-alpine AS builder

# Set working directory inside container
WORKDIR /app

# Install pnpm globally
RUN npm install -g pnpm

# Copy only necessary files to install dependencies
COPY pnpm-lock.yaml .
COPY pnpm-workspace.yaml .
COPY package.json .

# Install only backend dependencies (using workspace context)


COPY backend .

RUN pnpm install

WORKDIR /app/backend

CMD ["pnpm" , "run", "dev"]