export enum ServiceRequestStatus {
    OPEN = "OPEN",
    RESERVED = "RESERVED",
    CONFIRMED = "CONFIRMED",
    IN_PROGRESS = "IN_PROGRESS",
    COMPLETED = "COMPLETED",
    CANCELLED_BY_CLIENT = "CANCELLED_BY_CLIENT",
    CANCELLED_BY_WORKER = "CANCELLED_BY_WORKER",
    CANCELLED = "CANCELLED",
    EXPIRED = "EXPIRED",
    NO_WORKERS_AVAILABLE = "NO_WORKERS_AVAILABLE",
    ARCHIVED = "ARCHIVED"
}