export enum ServiceStatus {
    OPEN = "OPEN",
    CONFIRMED = "CONFIRMED",
    IN_PROGRESS = "IN_PROGRESS",
    COMPLETED = "COMPLETED",
    CANCELLED_BY_CLIENT = "CANCELLED_BY_CLIENT",
    CANCELLED_BY_WORKER = "CANCELLED_BY_WORKER",
    CANCELLED = "CANCELLED",
    EXPIRED = "EXPIRED",
}

export enum VideoCallStatus {
    SCHEDULED = "SCHEDULED",
    ONGOING = "ONGOING",
    ENDED = "ENDED",
    MISSED = "MISSED"
}