export enum ServiceStatus {
    PENDING = "PENDING",
    CONFIRMED = "CONFIRMED",
    IN_PROGRESS = "IN_PROGRESS",
    COMPLETED = "COMPLETED",
    CANCELLED_BY_CLIENT = "CANCELLED_BY_CLIENT",
    CANCELLED_BY_WORKER = "CANCELLED_BY_WORKER",
    CANCELLED = "CANCELLED",
    EXPIRED = "EXPIRED",
    NO_SHOW = "NO_SHOW",
    WORKER_ABSENT = "WORKER_ABSENT",
    CLIENT_ABSENT = "CLIENT_ABSENT",
}

export enum VideoCallStatus {
    SCHEDULED = "SCHEDULED",
    ONGOING = "ONGOING",
    ENDED = "ENDED",
    MISSED = "MISSED"
}